# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ff823cc07a2b8470c5ab63cff7778c1e170d868c26639ab6c1851c54a8c77095b27b0eca69bc66b53f59ca706c0bb045bf0197b3a1ea81f2fa1200803b83711e

test:
  secret_key_base: aaecb76c792fbb0b00248a9aaa7bfd657f75b17a5fdddf1d18645d99e2b79f1536f2a8d45630b0d232b864d04de7a4bb3e50e988057a9cb12f3149ce72defa6c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
